---
title: "Simulation"
author: "Young Geun Kim"
date: "`r format(Sys.time(), '%d %b, %Y')`"
output: 
  bookdown::html_document2:
    toc: true
knit:
  (function(inputFile, encoding) {
    rmarkdown::render(
      input = inputFile,
      output_dir = "../output", 
      encoding = encoding
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  out.width = "70%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = .618,
  fig.pos = "H"
)
knitr::knit_hooks$set(
  document = function(x) {
    sub("\\usepackage[]{color}", "\\usepackage{xcolor}", x, fixed = TRUE)
  }
)
options(digits = 3)
options(knitr.kable.NA = "")
options(kableExtra.latex.load_packages = FALSE)
is_html <- knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"
is_latex <- knitr::opts_knit$get("rmarkdown.pandoc.to") == "latex"
kable_format <- ifelse(!is_html, "latex", "html")
kable_format <- ifelse(length(kable_format) == 0, "html", kable_format) # for excecutable
```

```{r pkgs, message=FALSE}
# tidyverse----------------------------
library(tidyverse)
# BVHAR custom package-----------------
library(bvhar)
# set seed for reproducible result-----
set.seed(1)
# out of sample------------------------
h_step <- 10
```

```{r fns, message=FALSE}
# result table-------------------------
source("report-fns.R")
# hyperparameter setting table---------
source("param-fns.R")
```

# SMALL

## Import

```{r, message=FALSE}
# Train set
y_train <- read_csv("../data/processed/vharsim_small_train.csv")
# Evaluation set
y_test <- 
  read_csv("../data/processed/vharsim_small_test.csv") %>% 
  slice(1:h_step)
```

## Plot

```{r tsplot, echo=FALSE}
y_train %>% 
  mutate(train = TRUE) %>% 
  bind_rows(y_test %>% mutate(train = FALSE)) %>% 
  mutate(id = 1:n()) %>% 
  pivot_longer(-c(id, train), names_to = "asset", values_to = "value") %>% 
  ggplot(aes(x = id, y = value)) +
  annotate(
    geom = "rect",
    xmin = nrow(y_train),
    xmax = nrow(y_train) + nrow(y_test),
    ymin = -Inf,
    ymax = Inf,
    alpha = .7,
    fill = "grey" # test set
  ) +
  # geom_path(aes(colour = asset), show.legend = FALSE, alpha = .5) +
  geom_path() +
  facet_grid(asset ~ ., scales = "free_y") +
  scale_colour_viridis_d() +
  theme_minimal() +
  labs(
    x = element_blank(),
    y = element_blank()
  )
```

## Modeling

### VAR

```{r}
(var_lag <- 2)
```

```{r}
fit_var <- var_lm(y_train, var_lag, include_mean = FALSE)
pred_var <- predict(fit_var, h_step)
```

### VHAR

```{r}
fit_vhar <- vhar_lm(y_train, include_mean = FALSE)
pred_vhar <- predict(fit_vhar, h_step)
```

### BVAR

```{r}
(bvar_lag <- 2)
```

```{r}
(bvar_spec <- set_bvar(
  sigma = apply(y_train, 2, sd),
  lambda = .5,
  delta = rep(.1, ncol(y_train)),
  eps = 1e-04
))
```

```{r, cache=TRUE}
(bvar_optim <- choose_bvar(
  bvar_spec, 
  lower = c(
    rep(.0001, ncol(y_train)), # sigma
    .01, # lambda
    rep(.01, ncol(y_train)) # delta
  ), 
  upper = c(
    rep(1, ncol(y_train)), # sigma
    2, # lambda
    rep(1, ncol(y_train)) # delta
  ), 
  y = y_train, 
  p = bvar_lag, 
  include_mean = FALSE
))
```

```{r}
fit_bvar <- bvar_optim$fit
bvar_summary <- summary(fit_bvar)
pred_bvar <- predict(fit_bvar, h_step)
```

```{r residplot}
autoplot(fit_bvar, alpha = .5)
```

```{r bvarcoefplot}
autoplot(bvar_summary, var_name = "asset_01")
```

### BVHAR-VAR

```{r}
(bvhar_spec <- set_bvhar(
  sigma = apply(y_train, 2, sd),
  lambda = .5,
  delta = rep(.1, ncol(y_train)),
  eps = 1e-04
))
```

```{r, cache=TRUE}
(bvhar_var_optim <- choose_bvhar(
  bvhar_spec, 
  lower = c(
    rep(.0001, ncol(y_train)), # sigma
    .01, # lambda
    rep(.01, ncol(y_train)) # delta
  ), 
  upper = c(
    rep(1, ncol(y_train)), # sigma
    2, # lambda
    rep(1, ncol(y_train)) # delta
  ), 
  y = y_train, 
  include_mean = FALSE
))
```

```{r}
fit_bvhar_var <- bvhar_var_optim$fit
bvhar_var_summary <- summary(fit_bvhar_var)
pred_bvhar_var <- predict(fit_bvhar_var, h_step)
```

```{r bvharcoefplot1}
autoplot(bvhar_var_summary, var_name = "asset_01", NCOL = 3)
```

### BVHAR-VHAR

```{r}
(bvhar_spec_vhar <- set_weight_bvhar(
  sigma = apply(y_train, 2, sd),
  lambda = .5,
  eps = 1e-04,
  daily = rep(.1, ncol(y_train)),
  weekly = rep(.1, ncol(y_train)),
  monthly = rep(.1, ncol(y_train))
))
```

```{r, cache=TRUE}
(bvhar_vhar_optim <- choose_bvhar(
  bvhar_spec_vhar, 
  lower = c(
    rep(.0001, ncol(y_train)), # sigma
    .01, # lambda
    rep(.01, ncol(y_train)), # daily
    rep(.01, ncol(y_train)), # weekly
    rep(.01, ncol(y_train)) # monthly
  ), 
  upper = c(
    rep(1, ncol(y_train)), # sigma
    2, # lambda
    rep(1, ncol(y_train)), # daily
    rep(1, ncol(y_train)), # weekly
    rep(1, ncol(y_train)) # monthly
  ), 
  y = y_train, 
  include_mean = FALSE
))
```

```{r}
fit_bvhar_vhar <- bvhar_vhar_optim$fit
bvhar_vhar_summary <- summary(fit_bvhar_vhar)
pred_bvhar_vhar <- predict(fit_bvhar_vhar, h_step)
```

```{r bvharcoefplot2}
autoplot(bvhar_vhar_summary, var_name = "asset_01", NCOL = 3)
```

### Errors

```{r}
list(
  pred_var,
  pred_vhar,
  pred_bvar,
  pred_bvhar_var,
  pred_bvhar_vhar
) %>% 
  make_kable(y = y_test, error = "mse", format = kable_format)
```

```{r}
list(
  pred_var,
  pred_vhar,
  pred_bvar,
  pred_bvhar_var,
  pred_bvhar_vhar
) %>% 
  make_kable(y = y_test, error = "mae", format = kable_format)
```

```{r}
list(
  pred_var,
  pred_vhar,
  pred_bvar,
  pred_bvhar_var,
  pred_bvhar_vhar
) %>% 
  make_kable(y = y_test, error = "mape", format = kable_format)
```

```{r}
list(
  pred_var,
  pred_vhar,
  pred_bvar,
  pred_bvhar_var,
  pred_bvhar_vhar
) %>% 
  make_kable(y = y_test, error = "mase", format = kable_format)
```

```{r}
list(
  VAR = pred_var,
  VHAR = pred_vhar,
  BVAR = pred_bvar,
  BVHAR1 = pred_bvhar_var,
  BVHAR2 = pred_bvhar_vhar
) %>% 
  kable_lossmean(y = y_test, format = kable_format)
```


# MEDIUM

## Import

```{r, message=FALSE}
# Train set
medium_train <- read_csv("../data/processed/vharsim_medium_train.csv")
# Evaluation set
medium_test <- 
  read_csv("../data/processed/vharsim_medium_test.csv") %>% 
  slice(1:h_step)
```

## Plot

<!-- ```{r , echo=FALSE} -->
<!-- medium_train %>%  -->
<!--   mutate(train = TRUE) %>%  -->
<!--   bind_rows(medium_test %>% mutate(train = FALSE)) %>%  -->
<!--   mutate(id = 1:n()) %>%  -->
<!--   pivot_longer(-c(id, train), names_to = "asset", values_to = "value") %>%  -->
<!--   ggplot(aes(x = id, y = value)) + -->
<!--   # geom_path(aes(colour = train), show.legend = FALSE) + -->
<!--   # facet_grid(asset ~ ., scales = "free_y") + -->
<!--   annotate( -->
<!--     geom = "rect", -->
<!--     xmin = nrow(medium_train), -->
<!--     xmax = nrow(medium_train) + nrow(medium_test), -->
<!--     ymin = -Inf, -->
<!--     ymax = Inf, -->
<!--     alpha = .7, -->
<!--     fill = "grey" # test set -->
<!--   ) + -->
<!--   geom_path(aes(colour = asset), show.legend = FALSE, alpha = .5) + -->
<!--   scale_colour_viridis_d() + -->
<!--   theme_minimal() + -->
<!--   labs( -->
<!--     x = element_blank(), -->
<!--     y = element_blank() -->
<!--   ) -->
<!-- ``` -->

## Modeling

### VAR


### BVAR


### BVHAR





# LARGE

## Import

```{r, message=FALSE}
# Train set
large_train <- read_csv("../data/processed/vharsim_large_train.csv")
# Evaluation set
large_test <- read_csv("../data/processed/vharsim_large_test.csv")
```



