---
title: "Empirical Analysis"
author: "Young Geun Kim"
date: "`r format(Sys.time(), '%d %b, %Y')`"
output: 
  bookdown::html_document2:
    toc: true
knit:
  (function(inputFile, encoding) {
    rmarkdown::render(
      input = inputFile,
      output_dir = "../output", 
      encoding = encoding
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  out.width = "70%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = .618,
  fig.pos = "H"
)
knitr::knit_hooks$set(
  document = function(x) {
    sub("\\usepackage[]{color}", "\\usepackage{xcolor}", x, fixed = TRUE)
  }
)
options(digits = 3)
```

```{r}
library(tidyverse)
library(bvhar)
```

# Dataset

## Energy Consumption Data

```{r}
est_energy
```

## Plot

```{r}
est_energy %>% 
  mutate(id = 1:n()) %>% 
  pivot_longer(-id, names_to = "region", values_to = "rk") %>% 
  ggplot(aes(x = id, y = rk)) +
  geom_path(aes(colour = region), show.legend = FALSE) +
  theme_minimal()
```

Without `DEOK` (Daytok power and light componay),

```{r}
est_energy %>% 
  mutate(id = 1:n()) %>% 
  select(-DEOK) %>% 
  pivot_longer(-id, names_to = "region", values_to = "rk") %>% 
  ggplot(aes(x = id, y = rk)) +
  geom_path(aes(colour = region), show.legend = FALSE) +
  theme_minimal()
```

## Out-of-sample

```{r}
h <- 22
```

Exclude `DEOK`?

```{r}
est_eval <- 
  est_energy %>% 
  select(-DEOK) %>%
  divide_ts(h)
est_train <- est_eval$train
est_test <- est_eval$test
```

# Models

## VAR

```{r}
mod_var <- var_lm(est_train, 3)
forecast_var <- predict(mod_var, h)
mse_energy_var <- mse(forecast_var, est_test)
mean(mse_energy_var)
```

## VHAR

```{r}
mod_vhar <- vhar_lm(est_train)
forecast_vhar <- predict(mod_vhar, h)
mse_energy_vhar <- mse(forecast_vhar, est_test)
mean(mse_energy_vhar)
```

## BVAR

```{r}
spec_bvar <- set_bvar(
  sigma = apply(est_train, 2, sd),
  lambda = .2,
  delta = rep(.1, ncol(est_train))
)
# Empirical bayes------------------
(emp_bvar <- choose_bvar(
  spec_bvar,
  lower = .01,
  upper = 2,
  y = est_train,
  p = 3
))
```


```{r}
mod_bvar <- bvar_minnesota(est_train, 3, emp_bvar$spec)
forecast_bvar <- predict(mod_bvar, h)
mse_energy_bvar <- mse(forecast_bvar, est_test)
mean(mse_energy_bvar)
```

## BVHAR VAR-type

```{r}
spec_bvhar_var <- set_bvhar(
  sigma = apply(est_train, 2, sd),
  lambda = .2,
  delta = rep(.1, ncol(est_train))
)
# Empirical bayes--------------------
(emp_bvhar_var <- choose_bvhar(
  spec_bvhar_var,
  lower = .01,
  upper = 2,
  y = est_train
))
```

```{r}
mod_bvhar_var <- bvhar_minnesota(est_train, emp_bvhar_var$spec)
forecast_bvhar_var <- predict(mod_bvhar_var, h)
mse_energy_bvhar_var <- mse(forecast_bvhar_var, est_test)
mean(mse_energy_bvhar_var)
```

## BVHAR VHAR-type

```{r}
spec_bvhar_vhar <- set_weight_bvhar(
  sigma = apply(est_train, 2, sd),
  lambda = .2,
  daily = rep(.3, ncol(est_train)),
  weekly = rep(.2, ncol(est_train)),
  monthly = rep(.1, ncol(est_train))
)
# Empirical bayes-----------------------
(emp_bvhar_vhar <- choose_bvhar(
  spec_bvhar_vhar,
  lower = .01,
  upper = 2,
  y = est_train
))
```


```{r}
mod_bvhar_vhar <- bvhar_minnesota(est_train, emp_bvhar_vhar$spec)
forecast_bvhar_vhar <- predict(mod_bvhar_vhar, h)
mse_energy_bvhar_vhar <- mse(forecast_bvhar_vhar, est_test)
mean(mse_energy_bvhar_vhar)
```

## Result

```{r}
autoplot(forecast_var, x_cut = 990, ci_alpha = .7, type = "wrap") +
  autolayer(forecast_vhar, ci_alpha = .6) +
  autolayer(forecast_bvar, ci_alpha = .4) +
  autolayer(forecast_bvhar_var, ci_alpha = .3) +
  autolayer(forecast_bvhar_vhar, ci_alpha = .2) +
  theme(legend.position = "bottom") +
  scale_colour_viridis_d() +
  scale_fill_viridis_d()
```

# Evaluation

## MSE

```{r}
list(
  VAR = forecast_var,
  VHAR = forecast_vhar,
  BVAR = forecast_bvar,
  BVHAR1 = forecast_bvhar_var,
  BVHAR2 = forecast_bvhar_vhar
) %>% 
  lapply(function(PRED) mse(PRED, y = est_test) %>% mean()) %>% 
  unlist() %>% 
  sort()
```

```{r}
list(
  VAR = forecast_var,
  VHAR = forecast_vhar,
  BVAR = forecast_bvar,
  BVHAR1 = forecast_bvhar_var,
  BVHAR2 = forecast_bvhar_vhar
) %>% 
  plot_loss(y = est_test) +
  scale_y_log10() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

## MAE

```{r}
list(
  VAR = forecast_var,
  VHAR = forecast_vhar,
  BVAR = forecast_bvar,
  BVHAR1 = forecast_bvhar_var,
  BVHAR2 = forecast_bvhar_vhar
) %>% 
  lapply(function(PRED) mae(PRED, y = est_test) %>% mean()) %>% 
  unlist() %>% 
  sort()
```

```{r}
list(
  VAR = forecast_var,
  VHAR = forecast_vhar,
  BVAR = forecast_bvar,
  BVHAR1 = forecast_bvhar_var,
  BVHAR2 = forecast_bvhar_vhar
) %>% 
  plot_loss(y = est_test, type = "mae") +
  scale_y_log10() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

## MAPE

```{r}
list(
  VAR = forecast_var,
  VHAR = forecast_vhar,
  BVAR = forecast_bvar,
  BVHAR1 = forecast_bvhar_var,
  BVHAR2 = forecast_bvhar_vhar
) %>% 
  lapply(function(PRED) mape(PRED, y = est_test) %>% mean()) %>% 
  unlist() %>% 
  sort()
```

```{r}
list(
  VAR = forecast_var,
  VHAR = forecast_vhar,
  BVAR = forecast_bvar,
  BVHAR1 = forecast_bvhar_var,
  BVHAR2 = forecast_bvhar_vhar
) %>% 
  plot_loss(y = est_test, type = "mape") +
  scale_y_log10() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

## MASE

```{r}
list(
  VAR = forecast_var,
  VHAR = forecast_vhar,
  BVAR = forecast_bvar,
  BVHAR1 = forecast_bvhar_var,
  BVHAR2 = forecast_bvhar_vhar
) %>% 
  lapply(function(PRED) mase(PRED, y = est_test) %>% mean()) %>% 
  unlist() %>% 
  sort()
```

```{r}
list(
  VAR = forecast_var,
  VHAR = forecast_vhar,
  BVAR = forecast_bvar,
  BVHAR1 = forecast_bvhar_var,
  BVHAR2 = forecast_bvhar_vhar
) %>% 
  plot_loss(y = est_test, type = "mase") +
  scale_y_log10() +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

